### PR TITLE
build 2 outputs

### PR DESCRIPTION
**Pull request by 12rambau**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by 12rambau** [comment]
related to https://github.com/conda-forge/feedstock-outputs/pull/56 

@ocefpaf, I tried to apply the example you shared with me but I fear I didn't understand how to have 2 outputs in one single recipe. 

Could you give me a small insight from here?

**Comment by akhmerov** [comment]
I've stumbled upon a discussion about how to properly supply two packages from the same feedstock. It pointed to [this unmerged part of the docs](https://github.com/conda-forge/conda-forge.github.io/blob/4351560dd4cf6998d85630e2d3481da384dee13b/src/maintainer/knowledge_base.rst#L1362-L1385). I'll give a shot if changing the `name` variable fixes the issue.

**Review by akhmerov — COMMENTED** [review]
use same requirements

**Comment by akhmerov** [comment]
@conda-forge-admin, please rerender

**Comment by akhmerov** [comment]
I ended up copying the idea from https://github.com/conda-forge/typing_extensions-feedstock/blob/main/recipe/meta.yaml, which is listed as a good example of how to make an alias in https://github.com/conda-forge/conda-forge.github.io/issues/746

**Comment by 12rambau** [comment]
thanks very much @akhmerov for managing to make it work

**Comment by ocefpaf** [comment]
> Could you give me a small insight from here?

Sorry for being late here but this looks good. Thank you both for taking this one to the finish line!

**Pull request merged**
